<html>
    <form action="validaUsuario.php" method="POST">
        <div style="padding-top: 240px; padding-left: 440px;">
            <table>
                <tr>
                    <td>
                        Usuario:
                    </td>
                    <td>
                        <input type="email" name= "usuario" placeholder="e-mail"/>
                    </td>
                </tr>
                <br>
                <tr>
                    <td>
                    Senha:
                    </td>
                    <td>
                        <input type="password" name= "senha" placeholder="senha"/>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                    <input type="submit">
                    </td>
                </tr>
            </table>
        </div>
    </form>
</html>